name: my_weather
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.11
  get_it: ^7.2.0
  http: ^0.13.4
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  loading_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
